name: github-check

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10.0]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          pip install flake8
          pip install pytest
          pip install pytest-cov
          pip install requests_mock
          make build
          make package-install
      - name: Check lint
        run: make lint
      - name: Check Test
        run: make test